title: Dani♥Maps
description: 
author: Dani Trenado
github: https://github.com/darkalet
about: Soy geógrafo y analista SIG. Represento visualmente elementos espaciales para ayudar a la toma de decisiones. Y por diversión también :) 

enableTags: true
tagarray: [gis, qgis]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/da_nielet"
    - icon: fa-linkedin
      link: "www.linkedin.com/in/daniel-trenado-gutiérrez-a8a25128"
    - icon: fa-github
      link: "https://github.com/darkalet"

share:
  twitter_username: da_nielet
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://darkalet.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
